# Generated by Django 3.1.2 on 2021-08-30 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('membership_type', models.CharField(choices=[('Free', 'Free'), ('Standard', 'Standard'), ('Premium', 'Premium'), ('Professional', 'Professional')], default='Free', max_length=50)),
                ('membership_plan_id', models.CharField(blank=True, max_length=40, null=True)),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserMembershipSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('customer_code', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.membership')),
            ],
        ),
    ]
