# Generated by Django 3.2.8 on 2021-10-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_usermembershipsubscription_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usermembershipsubscription',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
