# Generated by Django 3.2.8 on 2021-10-22 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdomain', models.SlugField(unique=True)),
                ('domain', models.SlugField(blank=True, null=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('website_version', models.CharField(max_length=30)),
                ('tag', models.CharField(choices=[('Graphics', 'Graphics'), ('Web development', 'Web development'), ('UI/Ux', 'UI/Ux')], max_length=20)),
                ('image', models.ImageField(upload_to='home_page/portfolio_tag')),
                ('price', models.IntegerField(default=0)),
                ('paid', models.BooleanField(default=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.website')),
            ],
        ),
    ]
