# Generated by Django 3.2.8 on 2021-10-23 03:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='website/template')),
            ],
        ),
        migrations.RemoveField(
            model_name='websitetemplate',
            name='image',
        ),
        migrations.RemoveField(
            model_name='websitetemplate',
            name='website',
        ),
        migrations.AddField(
            model_name='website',
            name='template',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.websitetemplate'),
        ),
        migrations.AlterField(
            model_name='website',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='websitetemplate',
            name='website_version',
            field=models.CharField(choices=[('website_v1', 'website_v1')], default='website_v1', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='websitetemplate',
            name='file',
            field=models.ManyToManyField(to='website.TemplateFile'),
        ),
    ]
