# Generated by Django 3.2.8 on 2021-10-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20211023_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitetemplate',
            name='website_version',
            field=models.CharField(choices=[('website_v1', 'website_v1')], default='website_v1', max_length=30, unique=True),
        ),
    ]
