# Generated by Django 3.1.2 on 2021-08-30 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='post')),
                ('category', models.CharField(blank=True, choices=[('ED', 'Education'), ('EN', 'Entertainment'), ('L', 'Lifestyle'), ('MT', 'Modern technology')], max_length=3, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('like', models.IntegerField(default=0)),
                ('unlike', models.IntegerField(default=0)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('read_time', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_date', '-timestamp'],
            },
        ),
    ]
