# Generated by Django 3.1.2 on 2021-09-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagetestimonial',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepagetestimonial',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepagetestimonial',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
